### PR TITLE
updated directory protection and changed some cr/lf to lf

### PR DESCRIPTION
**Pull request by following5**

### CODE REVIEW

**Comment by following5** [comment]
This is mainly for adding protection to the new `src` and `vendor` dirs. The other files are only whitespace-cleaned.

**Comment by teiling88** [comment]
We don't need any protection for the src and vendor dir. Pls remove this .htaccess files.

**Comment by following5** [comment]
Are you sure that requests like http://test.opencaching.de/vendor/sebastian/comparator/composer.json or http://test.opencaching.de/src/Oc/Libse/Coordinate/TypeCoordinate.php should be allowed? This is forbidden for any other internal code directories like cache2, lib/lib2 etc.

**Comment by teiling88** [comment]
The composer.json is an information we already provide via our [composer.json](https://github.com/OpencachingDeutschland/oc-server3/blob/master/htdocs/composer.json) and in the src directory are only classes or functions so a call on a php file will nothing do.

**Comment by following5** [comment]
You know that because you set it up, but everyone else who will do a security review or who puts some file in the src directory may not know it. It wastes time, it is intransparent and creates a potential security risk. Also, it is very unusual to allow users access internal PHP scripts.

Please let's do it this way, consistent with all the other directories.

**Comment by teiling88** [comment]
another idea - should we create an global .htaccess file to manage all blocked directories? I don't realy like this boilerplate .htaccess files.

**Comment by mirsch** [comment]
I'm with @following5 on this topic. Usually `src` and `vendor` directories are placed outside the document root and not accessible through http. Especially the `vendor` dir may contain executable scripts e.g. `console`, `phpunit`, `phpcs` and so on. I think it's a good idea to keep it protected as long as it's inside the doc root and remove it as soon as doc root moves

**Comment by teiling88** [comment]
ok - no optimization i will merge it :-)

**Pull request merged**
