### PR TITLE
prevent false XSS detection; fixes #1137

### PR DESCRIPTION
**Pull request by following5**
### 1. Why is this change necessary?

see https://redmine.opencaching.de/issues/1137

high-prio fix, PR to stable

### 2. What does this change do, exactly?

see comments in added function OcSmarty::acceptsAndPurifiesHtmlInput()

### 4. Please link to the relevant issues (if any).

see https://redmine.opencaching.de/issues/1137

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have squashed any insignificant commits
- [x] This change has comments for package types, values, functions, and non-obvious lines of code

### CODE REVIEW

**Comment by following5** [comment]
I did not find out why Chrome just reacts to the log pages, not cache descriptions. Chrome's XSS heuristic seems somewhat mysterious.

Therefore I applied the fix to all pages which accept HTML input, to be sure that the problem will not reappear.

**Comment by teiling88** [comment]
What about this: https://redmine.opencaching.de/issues/1008 ?

**Comment by teiling88** [comment]
We have to check this after my vacation - i will merge and deploy it as a workaround.

**Comment by following5** [comment]
Redmine 1008 is not detected by browsers and must be fixed in OC code.  So this change does not affect 1008.

**Comment by following5** [comment]
Stable must be merged back to development to have this commit on devel sites, too.

**Comment by teiling88** [comment]
this was done one day for my vacation so the "backport" was done today :)

**Comment by following5** [comment]
thanks

**Pull request merged**
