### PR TITLE
moved stored-proc to /sql

### PR DESCRIPTION
**Pull request by following5**

### CODE REVIEW

**Comment by following5** [comment]
Not that this conflicts with #300. I will rebase the one or the other, whatever is merged first.

**Comment by teiling88** [comment]
are the files in die old directory in use?

**Comment by following5** [comment]
See my comments here: https://github.com/OpencachingDeutschland/oc-server3/pull/309/commits/83122734c17d60b7f42a75188cc6d71b5e9100ce#diff-c9f647fde2698478fc54374524602453

**Comment by following5** [comment]
Or do you mean the files in htdocs/doc/sql/stored-proc? They are all in use except for old/distance.sql, which is _currently_ not in use.

**Comment by teiling88** [comment]
ok thanks for your information

**Comment by following5** [comment]
will update the deployment scripts on all servers

**Pull request merged**
