### PR TITLE
okapi update

### PR DESCRIPTION
**Pull request by teiling88**
### 1. Why is this change necessary?

okapi update - please wait til it is merged in okapi repo

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have squashed any insignificant commits
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code

### CODE REVIEW

**Comment by following5** [comment]
> please wait til it is merged in okapi repo

... and then update this PR to the current OKAPI version berfore proceeding.

Can u add the "Don't merge" label?

**Comment by teiling88** [comment]
> ... and then update this PR to the current OKAPI version berfore proceeding.

this pr can't merged before it is updated - a unit test checks if the okapi has the version and revision flags. :-)

**Comment by following5** [comment]
So if e.g. ClanFamily hits the "merge" button now, he will get an error message and the merge will be rejected? Github says: "This pull request can be automatically merged by project collaborators".

**Comment by teiling88** [comment]
Three clicks to merge this pr: 
-> Click Merge pull request
-> check checkbox 
-> Confirm merge
image

**Comment by following5** [comment]
So the unit test is integrated into the Github workflow and triggers this confirmation form? Nice. :-)

**Comment by teiling88** [comment]
> So the unit test is integrated into the Github workflow and triggers this confirmation form? Nice. :-)

correct :-)

**Comment by following5** [comment]
Ist auf OCPL freigegeben und produziert Fehler. Woran liegt's?

KAPI caught the following exception while executing API method request.
This is an error in OUR code and should be fixed. Please contact the
developer of the module that threw this error. Thanks!

===== ERROR MESSAGE =====
ErrorException:
Argument 1 passed to okapi\services\caches\shortcuts\search_and_retrieve\WebService::call() must be an instance of okapi\core\Request\OkapiRequest, instance of okapi\Request\OkapiHttpRequest given
=========================

--- Stack trace ---
#0 /srv/ocpl/okapi/services/caches/shortcuts/search_and_retrieve/WebService.php(23): okapi\OkapiErrorHandler::handle(4096, 'Argument 1 pass...', '/srv/ocpl/okapi...', 23, Array)
#1 [internal function]: okapi\services\caches\shortcuts\search_and_retrieve\WebService::call(Object(okapi\Request\OkapiHttpRequest))
#2 /srv/ocpl/okapi/OkapiServiceRunner.php(137): call_user_func(Array, Object(okapi\Request\OkapiHttpRequest))
#3 /srv/ocpl/okapi/views/method_call/View.php(19): okapi\OkapiServiceRunner::call('services/caches...', Object(okapi\Request\OkapiHttpRequest))
#4 [internal function]: okapi\views\method_call\View::call('services/caches...')
#5 /srv/ocpl/okapi/lib/OkapiScriptEntryPointController.php(52): call_user_func_array(Array, Array)
#6 /srv/ocpl/okapi/index.php(46): okapi\lib\OkapiScriptEntryPointController::dispatch_request('/okapi/services...')
#7 {main}

--- OKAPI method called ---
/okapi/services/caches/shortcuts/search_and_retrieve
?langpref=pl%7Cen
&oauth_consumer_key=p9QkYcFzV7bWZemtJ5FT
&oauth_nonce=2cbda629e8a1abf8b6695f4bd0969e11
&oauth_signature_method=HMAC-SHA1
&oauth_timestamp=1505135159
&oauth_token=BPVtj5Cvre9HhurgF87D
&oauth_version=1.0
&retr_method=services%2Fcaches%2Fgeocaches
&retr_params=%7B%22fields%22%3A%20%22code%7Cname%7Clocation%7Ctype%7Cstatus%7Cdifficulty%7Cterrain%7Csize%7Csize2%7Cdate_hidden%7Ctrackables_count%7Cis_found%22%7D
&search_method=services%2Fcaches%2Fsearch%2Fbbox
&search_params=%7B%22bbox%22%3A%2254.079071%7C15.482435%7C54.113379%7C15.519515%22%2C%22exclude_my_own%22%3A%22true%22%2C%22found_status%22%3A%22notfound_only%22%2C%22ignored_status%22%3A%22notignored_only%22%7D
&wrap=true
&oauth_signature=qAw8Vzx3ugsLyQx4fdJKvt1FisU%3D

--- OKAPI version ---
1578 (e488974ec6be971ca575b2b80941d4abaf500378)

--- Request headers ---
Accept-Charset: utf-8,iso-8859-1;q=0.8,utf-16;q=0.8,*;q=0.7
Accept-Language: en-US,*;q=0.9
X-Requested-With: XMLHttpRequest
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:9.0.1) Gecko/20100101 Firefox/9.0.1
Host: opencaching.pl
Connection: Keep-Alive
Accept-Encoding: gzip
Cookie: ocpldata=eyJ1c2VyaWQiOjAsInVzZXJuYW1lIjoiIiwicGVybWFuZW50IjowLCJsYXN0bG9naW4iOiIiLCJzZXNzaW9uaWQiOiIiLCJhZG1pbiI6MCwibGFuZyI6InBsIn0%3D; PHPSESSID=06emae0e0f0l8hibfmuknv3sm2

**Comment by following5** [comment]
Ich verschiebe die weitere Diskussion nach https://github.com/opencaching/okapi/pull/503.

**Comment by following5** [comment]
The change is running stable now at OCPL.

Version numbers now are directly included in [master core/Okapi.php](https://github.com/opencaching/okapi/blob/master/okapi/core/Okapi.php), as long as the deployment script is not updated. So they are one step behind the last commit.

**Pull request merged**
