### PR TITLE
Feature/symfony integration field notes

### PR DESCRIPTION
**Pull request by mirsch**
This is a sample implementation and test for the Symfony Integration introduced in https://github.com/OpencachingDeutschland/oc-server3/pull/346.
It adds Field Note functionality (see http://redmine.opencaching.de/issues/143) but is far away from complete for now.
But it may give you an idea of the Symfony Framework and Doctrine e.g. Controllers, Entities, Migrations, Services and a more "Real World" Example of parallel installation to the legacy code.

In addition to the notes in https://github.com/OpencachingDeutschland/oc-server3/pull/346
make sure to copy `app/config/parameters.yml.dist` to `app/config/parameters.yml` and adjust database settings. After this cd into htdocs and run `bin/console doctrine:migrations:migrate` to execute the migration(s) and update your database.
~~For now you manually have to add the SQL for the menu item. So please run
INSERT INTO `sys_menu` (`id`, `id_string`, `title`, `title_trans_id`, `menustring`, `menustring_trans_id`, `access`, `href`, `visible`, `parent`, `position`, `color`, `sitemap`, `only_if_parent`)
VALUES (109, 'MNU_MYPROFILE_FIELD_NOTES', 'Field Notes', 0, 'Field Notes', 0, 0, '/field-notes/', 1, 9, 11, '', 1, NULL);~~

You may download translations from https://crowdin.com/project/opencaching/ and place them in `htdocs/app/Resources/translations/`

Browse to http://local.opencaching.de/field-notes/ to manage your field notes.

### CODE REVIEW

**Comment by teiling88** [comment]
pls comine/squash your commits if it is possible

**Comment by mirsch** [comment]
I just opened this PR for Review/Information it's "work in progress" [WIP] And should not be merged because the feature is not ready yet.

**Comment by teiling88** [comment]
ups my fault :)

**Comment by mirsch** [comment]
@teiling88 It's now ready to review

**Pull request closed without merging**
