### PR TITLE
add symfony console and phpcs wrapper command

### PR DESCRIPTION
**Pull request by mirsch**
This adds the symfony console component as preparation for migrating legacy cli scripts e.g. cron scripts
As an example and useful tool, which should be integrated in continuous integration (CI) later, I've added a wrapper command for `phpcs`

**Prerequisites:**
current VM was missing the `patch` command. To test this code you'll have to `sudo yum install patch` , `provison.sh` is adjusted in this commit. Remember to run `composer install`

**How to use:**
`cd /var/www/html/htdocs`
run
`bin/console` to get an overview of possible commands
run
`bin/console code:sniff` this will test the `src/` folder against PSR-2 rules.
bildschirmfoto 2016-05-19 um 21 46 48
violations marked with `[x]` can be fixed automatically.
run
`bin/console code:sniff -f` to fix them

**How to add your own commands**
- Create the command in src/Oc/Console/Command
- register your command in `bin/console` by adding it to the application e.g. `$application->add(new CodeSnifferCommand());`

### CODE REVIEW

**Comment by following5** [comment]
Are you sure that this should be installed in `htdocs/bin`, not one level higher in `bin`?

**Comment by mirsch** [comment]
Well, `bin/console` is usually parallel to `vendor` and `src` dirs. But I'm fine with moving it to `bin` as long as `htdocs` is the document root.

**Comment by following5** [comment]
Ok, thanks. This saves us from another .htaccess file.

It's nice. :) I already used the phpcs from your branch for fa7ba4a (but did the fixes manually).

**Comment by following5** [comment]
Maybe `src`, `vendor` and other stuff like `cache` and `var` also should be moved one level up, with `htdocs` staying the document root (as its name says).

**Comment by mirsch** [comment]
👍

**Pull request merged**
