### PR TITLE
Misc/update okapi

### PR DESCRIPTION
**Pull request by teiling88**
### 1. Why is this change necessary?

okapi update :-)

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have squashed any insignificant commits
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code

### CODE REVIEW

**Comment by following5** [comment]
Es kann sein dass hier nochmal ein Rollback kommt, falls der Change nicht stabil auf Opencaching.pl läuft. Ich muss die jetzt erst mal überzeugen, mein manuelles OKAPI-Update zu akzeptieren.

**Comment by teiling88** [comment]
Ok, thank you!

**Comment by following5** [comment]
The change now runs stable on OCPL sites, "go" for OCDE merge.

Automatic OKAPI deployment is still broken; needs manual action by wrygiel.

**Comment by teiling88** [comment]
thank you again for your work on oc.pl side. I will merge this and deploy the other stuff in the evening.

**Comment by teiling88** [comment]
the new version is merged and live on opencaching.de

**Comment by following5** [comment]
http://bit.ly/2eKPhaw -> http://bit.ly/2j7Zra8 -> http://bit.ly/2wLPBzO -> http://bit.ly/2xSk1Pb  :-$

Case changes are evil.

**Comment by teiling88** [comment]
i don't get it. It seems this person did't know what he does?

**Pull request merged**
